# Added by ForgeCode installer. Use $HOME rather than an OS-specific absolute
# home path so this works on macOS too.
export PATH="$HOME/.local/bin:$PATH"
export COLORTERM=truecolor

################################################################################
# zsh stuff
################################################################################

################################################################################
# OS-specific rc (sourced early so FZF_BASE, named dirs apply before plugins
# load)
################################################################################
case "$OSTYPE" in
darwin*) [[ -f "${HOME}/.config/zsh/rc.macos.zsh" ]] && source "${HOME}/.config/zsh/rc.macos.zsh" ;;
linux*) [[ -f "${HOME}/.config/zsh/rc.linux.zsh" ]] && source "${HOME}/.config/zsh/rc.linux.zsh" ;;
esac

################################################################################
# cached generated completions
################################################################################
# Keep fpath unique as completion dirs are prepended by shell config, plugins,
# Homebrew, and tool-specific setup snippets.
typeset -aU fpath

ZSH_COMPLETION_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/completions"
mkdir -p "$ZSH_COMPLETION_CACHE_DIR"

_zsh_completion_dirs=(
  "$ZSH_COMPLETION_CACHE_DIR"
  "$HOME/.zfunc"
  ${HOMEBREW_PREFIX:+"$HOMEBREW_PREFIX/share/zsh-completions"}
  ${HOMEBREW_PREFIX:+"$HOMEBREW_PREFIX/share/zsh/site-functions"}
  /home/linuxbrew/.linuxbrew/share/zsh-completions
  /home/linuxbrew/.linuxbrew/share/zsh/site-functions
  /usr/local/share/zsh/site-functions
  /usr/share/zsh/site-functions
  /usr/share/zsh/vendor-completions
)
_zsh_existing_fpath=("${fpath[@]}")
fpath=()
for dir in "${_zsh_completion_dirs[@]}"; do
  [[ -d "$dir" ]] && fpath+=("$dir")
done
fpath+=("${_zsh_existing_fpath[@]}")
unset dir _zsh_completion_dirs _zsh_existing_fpath

_zsh_comp_regen_needed=0
# Usage: regen_zsh_completion_if_needed <cmd> [generator args…]
#        regen_zsh_completion_if_needed <name>=<cmd> [generator args…]
# The name=cmd form is for completions generated by a different binary
# (e.g. cargo=rustup completions zsh cargo → writes _cargo, runs rustup).
regen_zsh_completion_if_needed() {
  local spec="$1"
  shift
  local name="${spec%%=*}"
  local cmd="${spec#*=}"
  local -a gen=("$cmd")
  local outfile="$ZSH_COMPLETION_CACHE_DIR/_$name"
  local tmpfile

  if (($#)); then
    gen+=("$@")
  else
    gen+=(completion zsh)
  fi

  command -v "$cmd" >/dev/null 2>&1 || return 0

  # regenerate if missing, empty, or if the binary is newer than the cached completion
  if [[ ! -s "$outfile" || "$(command -v "$cmd")" -nt "$outfile" ]]; then
    tmpfile="${outfile}.$$.tmp"
    if "${gen[@]}" 2>/dev/null | sed '/./,$!d; s/`/\\`/g' >|"$tmpfile" && [[ -s "$tmpfile" ]]; then
      command mv -f "$tmpfile" "$outfile"
      _zsh_comp_regen_needed=1
    else
      command rm -f "$tmpfile"
    fi
  fi
}

# tools that support: <tool> completion zsh
# (helper no-ops when not installed)
regen_zsh_completion_if_needed agentsview
regen_zsh_completion_if_needed bd
regen_zsh_completion_if_needed dcg
regen_zsh_completion_if_needed docbank
regen_zsh_completion_if_needed docker
regen_zsh_completion_if_needed helm
regen_zsh_completion_if_needed herdr
regen_zsh_completion_if_needed kata
regen_zsh_completion_if_needed kind
regen_zsh_completion_if_needed kubectl
regen_zsh_completion_if_needed kwt
regen_zsh_completion_if_needed mise
regen_zsh_completion_if_needed msgvault
regen_zsh_completion_if_needed openclaw
regen_zsh_completion_if_needed pvez
regen_zsh_completion_if_needed roborev
regen_zsh_completion_if_needed tailscale
regen_zsh_completion_if_needed yas

# tools with non-default generator invocations
regen_zsh_completion_if_needed gh completion -s zsh
regen_zsh_completion_if_needed rustup completions zsh
regen_zsh_completion_if_needed cargo=rustup completions zsh cargo
regen_zsh_completion_if_needed task --completion zsh

# invalidate oh-my-zsh's compinit cache if any completions were regenerated
# (files only: the compinit .lock next to them is a directory)
if ((_zsh_comp_regen_needed)); then
  command rm -f ~/.zcompdump*(N.)
fi
unset _zsh_comp_regen_needed

# oh-my-zsh installation path
export ZSH="${HOME}/.oh-my-zsh"

################################################################################
# zsh history
################################################################################
setopt no_flow_control

################################################################################
# fzf configuration (before plugins)
################################################################################
# Enhanced Ctrl+R history search
export FZF_CTRL_R_OPTS="--preview 'echo {}' --preview-window up:3:wrap --bind 'ctrl-/:toggle-preview' --border"
export FZF_DEFAULT_OPTS="--height=40% --layout=reverse --border --bind 'ctrl-/:toggle-preview'"

################################################################################
# oh-my-zsh plugins
################################################################################

# pre-req:
#   git clone https://github.com/eliyastein/llm-zsh-plugin ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/llm

# fzf's key-bindings/completion scripts save+restore all options including
# `zle`, which errors ("can't change option: zle") in tty-less interactive
# shells (zsh -ic from scripts/agents). Keybindings need a tty anyway.
plugins=()
[[ -t 0 || -t 1 ]] && plugins+=(fzf)
plugins+=(
  fzf-tab
  # `git` plugin intentionally omitted: it defines ~190 g* aliases (grm, gwipe,
  # gpristine, …) that are mostly foot-guns. I type full git commands. Keep a
  # hand-picked few in ~/.config/aliases.sh instead.
  history-substring-search
  zsh-autosuggestions
  zsh-syntax-highlighting
  zsh-shift-select
  llm
)

# Oh My Zsh runs compinit during startup after adding plugin completion dirs to fpath.
# Do not add a separate compinit here unless intentionally overriding that behavior.
source "$ZSH/oh-my-zsh.sh"

# history-substring-search keybindings (must be after plugin load)
bindkey '^[[A' history-substring-search-up
bindkey '^[OA' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey '^[OB' history-substring-search-down
[[ -n "$terminfo[kcuu1]" ]] && bindkey "$terminfo[kcuu1]" history-substring-search-up
[[ -n "$terminfo[kcud1]" ]] && bindkey "$terminfo[kcud1]" history-substring-search-down

################################################################################
# Enhanced History Configuration
################################################################################
HISTSIZE=100000             # In-memory history (larger for better search)
SAVEHIST=100000             # On-disk history (match in-memory)
setopt INC_APPEND_HISTORY   # Write to history immediately, not on shell exit
setopt HIST_FIND_NO_DUPS    # Don't show duplicates when searching history
setopt HIST_REDUCE_BLANKS   # Remove extra whitespace from commands
setopt HIST_IGNORE_ALL_DUPS # Remove older duplicate when adding new entry

################################################################################
# Enhanced Completion Configuration
################################################################################
# Completion formatting and grouping
zstyle ':completion:*' menu select
# Smart-case matching: typed lowercase matches either case; typed uppercase is
# exact. Deliberately NOT the bidirectional 'm:{a-zA-Z}={A-Za-z}': that matcher
# makes compsys invent bogus uppercase chars in the unambiguous prefix when
# candidates diverge (e.g. `gcloud compute in<Tab>` inserted a literal "T").
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' format '%F{yellow}-- %d --%f'
zstyle ':completion:*' group-name ''
zstyle ':completion:*:descriptions' format '%F{green}-- %d --%f'
zstyle ':completion:*:warnings' format '%F{red}-- no matches --%f'
zstyle ':completion:*:corrections' format '%F{yellow}-- %d (errors: %e) --%f'
[[ -n "$LS_COLORS" ]] && zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

# More forgiving completion behavior
_comp_options+=(globdots)
setopt AUTO_MENU
setopt COMPLETE_IN_WORD
setopt ALWAYS_TO_END

# fzf-tab enhancements - fuzzy file previews
zstyle ':fzf-tab:*' fzf-flags --height=50% --layout=reverse --border
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'lsd -1 --color=always $realpath 2>/dev/null || ls -1 --color=always $realpath'
zstyle ':fzf-tab:complete:*:*' fzf-preview 'bat --color=always --style=numbers --line-range=:100 $realpath 2>/dev/null || lsd -la --color=always $realpath 2>/dev/null || echo $word'

# Switch group with < and >
zstyle ':fzf-tab:*' switch-group '<' '>'

################################################################################
# Carapace fallback completions
################################################################################
if command -v carapace >/dev/null 2>&1; then
  export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense'

  # Self-heal the zsh bridge cache. Carapace's zsh bridge seeds
  # ~/.config/carapace/bridge/zsh/.zcompdump_capture from ~/.zcompdump; if that
  # dump was ever written while carapace was loaded, the capture maps thousands
  # of commands to _carapace_completer — a function that does not exist inside
  # the bridge shell. Completing any bridged command then yields
  # "(eval):1: command not found: _carapace_completer" as the only "match", and
  # compinit keeps trusting the poisoned capture because its #files count still
  # matches. Deleting it forces a clean regeneration on next use.
  _carapace_bridge_capture="${XDG_CONFIG_HOME:-$HOME/.config}/carapace/bridge/zsh/.zcompdump_capture"
  if [[ -f "$_carapace_bridge_capture" ]] &&
    grep -qm1 '_carapace_completer' "$_carapace_bridge_capture" 2>/dev/null; then
    rm -f "$_carapace_bridge_capture"
  fi
  unset _carapace_bridge_capture

  source <(carapace _carapace zsh)

  # Carapace is broad by design; keep generated/native completions in front for
  # the tools this config explicitly caches.
  if (($+functions[compdef])); then
    # Every completion generated into $ZSH_COMPLETION_CACHE_DIR above wins over
    # carapace. Derived from the directory rather than a hand-kept list so a new
    # regen_zsh_completion_if_needed entry doesn't silently fall through to
    # carapace (which then bridges back out to a zsh subshell per Tab).
    for comp in "$ZSH_COMPLETION_CACHE_DIR"/_*(N.); do
      cmd="${${comp:t}#_}"
      command -v "$cmd" >/dev/null 2>&1 && compdef "_$cmd" "$cmd"
    done
    unset comp cmd

    _zsh_native_completion_pairs=(
      # Path-heavy commands: carapace 1.6.6+ double-escapes spaces in zsh
      # output, so restore native completion for the common file tools.
      cat:_cat
      ls:_ls
      cp:_cp
      mv:_mv
      rm:_rm
      ln:_ln
      mkdir:_mkdir
      rmdir:_rmdir
      touch:_touch
      chmod:_chmod
      chown:_chown
      stat:_stat
      head:_head
      tail:_tail
      less:_less
      vim:_vim
      vi:_vi
      find:_find
      tree:_tree
      tar:_tar
      zip:_zip
      gzip:_gzip
      grep:_grep
      du:_du
      wc:_wc
      diff:_diff
      sort:_sort
      uniq:_uniq
      open:_open
      jq:_jq
      xargs:_xargs
      readlink:_readlink
      basename:_basename
      rsync:_rsync
    )
    for pair in "${_zsh_native_completion_pairs[@]}"; do
      cmd="${pair%%:*}"
      comp="${pair#*:}"
      whence -w "$comp" >/dev/null 2>&1 && compdef "$comp" "$cmd"
    done
    # Tools without a native zsh completer: fall back to plain file completion
    # rather than carapace (still avoids the double-escape bug).
    _zsh_files_only_cmds=(
      nvim
      nano
      bat
      lsd
      rg
      fd
      more
      unzip
      gunzip
      xdg-open
      realpath
      dirname
    )
    for cmd in "${_zsh_files_only_cmds[@]}"; do
      compdef _files "$cmd"
    done
    unset cmd comp pair _zsh_native_completion_pairs _zsh_files_only_cmds
  fi
fi

compdebug() {
  local cmd="$1"

  if [[ -z "$cmd" ]]; then
    echo "usage: compdebug <command>"
    return 1
  fi

  echo "command:"
  whence -v "$cmd" || return 1

  echo
  # The actual winner: whoever compdef'd last wins, regardless of what exists in
  # fpath. If this says _carapace_completer, completion is going out to a
  # carapace bridge subshell rather than using a local completion.
  echo "registered completer (_comps):"
  echo "${_comps[$cmd]:-<none — falls back to _default>}"

  echo
  echo "zsh completion function:"
  local comp="_$cmd"
  whence -v "$comp" || echo "No _$cmd found in fpath"

  echo
  echo "fpath entries containing possible completion:"
  local dir
  for dir in $fpath; do
    [[ -e "$dir/_$cmd" ]] && echo "$dir/_$cmd"
  done

  echo
  echo "carapace:"
  if command -v carapace >/dev/null 2>&1; then
    carapace "$cmd" --help >/dev/null 2>&1 &&
      echo "Carapace appears to know about $cmd" ||
      echo "No obvious Carapace completer for $cmd"
  else
    echo "carapace not installed"
  fi
}

################################################################################
# zsh-vim-mode
################################################################################
# esc-esc immediately switches to NORMAL mode
bindkey -rpM viins '^[^['

################################################################################
# GPG/SSH
################################################################################

# GPG (signing only, not used for SSH)
export GPG_TTY=$(tty)

# SSH agent - start one if not already running
if [[ -z "$SSH_AUTH_SOCK" || ! -S "$SSH_AUTH_SOCK" ]]; then
  eval "$(ssh-agent -s)" >/dev/null 2>&1
fi

################################################################################
# alias/fns
################################################################################
[[ -f "${HOME}/.config/aliases.sh" ]] && source "${HOME}/.config/aliases.sh"

################################################################################
# API Keys (loaded from ~/.secrets - not tracked in dotfiles repo)
################################################################################
[[ -f "${HOME}/.secrets" ]] && source "${HOME}/.secrets"

################################################################################
# local overrides
################################################################################
[[ -f "${HOME}/.zshrc.local" ]] && source "${HOME}/.zshrc.local"

# x-cmd - only source once (guarded to prevent duplicate loading)
[[ -z "$X_CMD_SOURCED" ]] && [[ -f "$HOME/.x-cmd.root/X" ]] && . "$HOME/.x-cmd.root/X" && export X_CMD_SOURCED=1

################################################################################
# prompt (oh-my-posh)
# Theme resolution is portable across machines (first match wins):
#   1. ~/.config/oh-my-posh/themes   custom themes, yadm-tracked (same path on every OS)
#   2. oh-my-posh's built-in default
# Pick a different theme per-machine by setting OMP_THEME_NAME in ~/.zshrc.local.
# Degrades to a plain prompt when oh-my-posh isn't installed.
################################################################################
: "${OMP_THEME_NAME:=tokyonight.omp.json}"
if command -v oh-my-posh >/dev/null 2>&1; then
  _omp_config=""
  for _omp_dir in "$HOME/.config/oh-my-posh/themes"; do
    [[ -n "$_omp_dir" && -f "$_omp_dir/$OMP_THEME_NAME" ]] && {
      _omp_config="$_omp_dir/$OMP_THEME_NAME"
      break
    }
  done
  if [[ -n "$_omp_config" ]]; then
    eval "$(oh-my-posh init zsh --config "$_omp_config")"
  else
    eval "$(oh-my-posh init zsh)"
  fi
  # Survive `brew upgrade oh-my-posh` in already-open shells. oh-my-posh bakes
  # its version-stamped path (…/Cellar/oh-my-posh/<ver>/bin/oh-my-posh) into the
  # init it generates; brew deletes that dir on upgrade, so every running shell
  # then spews "_omp_preexec: no such file or directory" on each command. The
  # PATH symlink is relinked to the new version in place, so re-point the prompt
  # at it. The init's hot-path functions read $_omp_executable at call time, so
  # reassigning the variable is all that's needed.
  [[ -n "$_omp_executable" ]] && _omp_executable="$(command -v oh-my-posh)"
  unset _omp_config _omp_dir
fi

# AI-usage prompt segment — optional; self-disables when its data source is absent.
[[ -r "$HOME/.config/oh-my-posh/ai-usage.zsh" ]] && source "$HOME/.config/oh-my-posh/ai-usage.zsh"
# Codex 5h/weekly usage — optional; refreshed in the background for the prompt.
[[ -r "$HOME/.config/oh-my-posh/codex-limits.zsh" ]] && source "$HOME/.config/oh-my-posh/codex-limits.zsh"
# Claude Code 5h/weekly usage — optional; hidden until a Claude Code session populates the snapshot.
[[ -r "$HOME/.config/oh-my-posh/claude-limits.zsh" ]] && source "$HOME/.config/oh-my-posh/claude-limits.zsh"

# GitHub CLI - load auth token into GH_TOKEN
if command -v gh >/dev/null 2>&1; then
  export GH_TOKEN="$(gh auth token 2>/dev/null)"
fi

# Mise
if command -v mise >/dev/null 2>&1; then
  eval "$(mise activate zsh)"
fi

# bun completions
[[ -s "$HOME/.oh-my-zsh/completions/_bun" ]] && source "$HOME/.oh-my-zsh/completions/_bun"

#compdef opencode
###-begin-opencode-completions-###
#
# yargs command completion script
#
# Installation: opencode completion >> ~/.zshrc
#    or opencode completion >> ~/.zprofile on OSX.
#
_opencode_yargs_completions() {
  local reply
  local si=$IFS
  IFS=$'
' reply=($(COMP_CWORD="$((CURRENT - 1))" COMP_LINE="$BUFFER" COMP_POINT="$CURSOR" opencode --get-yargs-completions "${words[@]}"))
  IFS=$si
  if [[ ${#reply} -gt 0 ]]; then
    _describe 'values' reply
  else
    _default
  fi
}
if [[ "'${zsh_eval_context[-1]}" == "loadautofunc" ]]; then
  _opencode_yargs_completions "$@"
else
  compdef _opencode_yargs_completions opencode
fi
###-end-opencode-completions-###

# >>> forge initialize >>>
# !! Contents within this block are managed by 'forge zsh setup' !!
# !! Do not edit manually - changes will be overwritten !!

# Add required zsh plugins if not already present
if [[ ! " ${plugins[@]} " =~ " zsh-autosuggestions " ]]; then
  plugins+=(zsh-autosuggestions)
fi
if [[ ! " ${plugins[@]} " =~ " zsh-syntax-highlighting " ]]; then
  plugins+=(zsh-syntax-highlighting)
fi

# Load forge shell plugin (commands, completions, keybindings) if not already loaded
if [[ -z "$_FORGE_PLUGIN_LOADED" ]] && command -v forge >/dev/null 2>&1; then
  eval "$(forge zsh plugin)"
fi

# Load forge shell theme (prompt with AI context) if not already loaded
if [[ -z "$_FORGE_THEME_LOADED" ]] && command -v forge >/dev/null 2>&1; then
  eval "$(forge zsh theme)"
fi
# <<< forge initialize <<<

# Tab: forge's @file / :command pickers, else fzf-tab. Forge's own Tab widget
# (forge-completion, bound in the managed block above) falls through to plain
# expand-or-complete, which bypasses fzf-tab and its zstyles entirely. Must
# stay after the forge block so this binding wins.
if (( $+widgets[fzf-tab-complete] )); then
  function forge-or-fzf-tab-completion() {
    local current_word="${LBUFFER##* }"
    if (( $+widgets[forge-completion] )) &&
      [[ "$current_word" == @* || "$LBUFFER" =~ "^:([a-zA-Z][a-zA-Z0-9_-]*)?$" ]]; then
      zle forge-completion
    else
      zle fzf-tab-complete
    fi
  }
  zle -N forge-or-fzf-tab-completion
  bindkey '^I' forge-or-fzf-tab-completion
fi

################################################################################
# Zoxide
################################################################################

command -v zoxide >/dev/null 2>&1 && eval "$(zoxide init zsh)"

# yas shell-history capture (https://github.com/mjacobs/yas)
[[ -f ~/.config/yas/hook.zsh ]] && source ~/.config/yas/hook.zsh
# yas Ctrl-R recall over yas history (sourced after oh-my-zsh/fzf so this
# ^R binding wins; up-arrow stays vanilla zsh). Set YAS_FZF_EXECUTOR='' for all.
[[ -f ~/.config/yas/ctrl-r.zsh ]] && source ~/.config/yas/ctrl-r.zsh

# dcg: warn if hook was silently removed from Claude Code settings
if command -v dcg &>/dev/null && command -v jq &>/dev/null; then
  if [ -f "$HOME/.claude/settings.json" ] &&
    ! jq -e '.hooks.PreToolUse[]? | select(.hooks[]?.command | test("dcg$"))' \
      "$HOME/.claude/settings.json" &>/dev/null; then
    printf '\033[1;33m[dcg] Hook missing from ~/.claude/settings.json — run: dcg install\033[0m\n'
  fi
fi
# leaf completions are optional and installed below each machine's home.
if [[ -f "$HOME/.local/share/leaf/completions/_leaf" ]]; then
  source "$HOME/.local/share/leaf/completions/_leaf"
fi
