r cycle_values video-rotate 90 180 270 0

Alt+6 script-message Quick_Scale "1024" "768" "0.2" "-1"
Alt+7 script-message Quick_Scale "1280" "800" "0.33" "-1"
Alt+8 script-message Quick_Scale "1280" "800" "0.5" "-1"
Alt+9 script-message Quick_Scale "1280" "800" "0.75" "-1"
Alt+0 script-message Quick_Scale "1600" "1200" "1" "-1"
