-- return {
--   "mjacobs/mru-nav.nvim",
--   dev = true,
--   cmd = { "MruFile", "MruBuffer", "MruClearFiles" },
--   keys = {
--     { "<leader>mf", function() require("mru_nav").mru_files() end, desc = "MRU file picker" },
--     { "<leader>mb", function() require("mru_nav").mru_buffers() end, desc = "MRU buffer picker" },
--   },
--   opts = {},
-- }
